### ISSUE TITLE
Examples are not working

### ISSUE THREAD

**Issue by tmdroid** [IonicaBizau/tithe#14]
Hey! I see a little issue with the examples you provide in the way that they don't seem to be working. Here's a screenshot to demonstrate. I also checked the `~/.tithe.json` file and it's empty after the insertion command.

![screenshot from 2017-09-12 04 55 21](https://user-images.githubusercontent.com/6765362/30304523-9a7d8408-9776-11e7-904e-a0e5c26c6824.png)

**Comment by IonicaBizau** [comment]
I forgot to update the examples! 🙈

**Comment by IonicaBizau** [comment]
`npm i -g tithe@latest` should fix it.
